DROP DATABASE IF EXISTS elections;
CREATE DATABASE `elections`;
USE `elections`;

CREATE TABLE user (
id INT(20) NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
patronymic VARCHAR(50),
street VARCHAR(50) NOT NULL,
numberHouse VARCHAR(50) NOT NULL,
numberFlat VARCHAR(50),
login VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
nomination enum('NOT_NOMINATED','NOMINATED') NOT NULL,
PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE session (
id INT(20) NOT NULL AUTO_INCREMENT,
token VARCHAR(40) NOT NULL,
idUser INT(20) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE candidate (
id INT(20) NOT NULL AUTO_INCREMENT,
consentToNomination enum('AGREE','DISAGREE') NOT NULL,
idUser INT(20) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE program (
id INT(20) NOT NULL AUTO_INCREMENT,
idUser INT(20) NOT NULL,
FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE,
PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE proposal (
id INT(20) NOT NULL AUTO_INCREMENT,
proposal VARCHAR(100) NOT NULL,
idUser INT(20) NOT NULL,
idProgram INT(20),
PRIMARY KEY (id),
FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE,
FOREIGN KEY (idProgram) REFERENCES program (id) ON DELETE SET NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE evaluationProposal (
id INT(20) NOT NULL AUTO_INCREMENT,
idUser INT(20) NOT NULL,
idProposal INT(20) NOT NULL,
rating INT(20) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE,
FOREIGN KEY (idProposal) REFERENCES proposal (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE programProposal (
id INT(20) NOT NULL AUTO_INCREMENT,
idProgram INT(20) NOT NULL,
idProposal INT(20) NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY program_proposal (idProgram,idProposal),
FOREIGN KEY (idProgram) REFERENCES program (id) ON DELETE CASCADE,
FOREIGN KEY (idProposal) REFERENCES proposal (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE voting (
idUser INT(20) NOT NULL UNIQUE,
idCandidate INT(20),
FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE,
FOREIGN KEY (idCandidate) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;